- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Update APT package manager
      apt:
        update_cache: yes
        cache_valid_time: 3600

    # - name: Install Node.js and npm
    #   apt:
    #     name:
    #       - nodejs
    #       - npm
    #     state: present

    # - name: Install MongoDB
    #   apt:
    #     name: mongodb
    #     state: present

    - name: Clone the repository
      git:
        repo: 'https://github.com/K-S-VICKY/graphql'
        dest: /var/www/task-manager-api
        version: main

    - name: Install project dependencies
      npm:
        path: /var/www/task-manager-api
        state: present

    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes

    - name: Start the application with PM2
      command: pm2 start src/app.js --name task-manager
      args:
        chdir: /var/www/task-manager-api

    - name: Save PM2 process list
      command: pm2 save
